/* Copyright 2010 Wageningen University, Division of Human Nutrition.
 * Drs. R. Kerkhoven, robert.kerkhoven@wur.nl
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ctd.model;
// Generated 4-feb-2010 11:21:21 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;


/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements Serializable {


     private Integer id;
     private String ctdRef;
     private String folder;
     private String password;
     private String closed;
     private String title;

    

     private List studySampleAssaies = new ArrayList();

    public Ticket() {
    }

	
    public Ticket(String ctdRef, String folder, String password) {
        this.ctdRef = ctdRef;
        this.folder = folder;
        this.password = password;
    }
    public Ticket(String ctdRef, String folder, String password, List studySampleAssaies) {
       this.ctdRef = ctdRef;
       this.folder = folder;
       this.password = password;
       this.studySampleAssaies = studySampleAssaies;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCtdRef() {
        return this.ctdRef;
    }
    
    public void setCtdRef(String ctdRef) {
        this.ctdRef = ctdRef;
    }
    public String getFolder() {
        return this.folder;
    }
    
    public void setFolder(String folder) {
        this.folder = folder;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public List getStudySampleAssaies() {
        return this.studySampleAssaies;
    }
    
    public void setStudySampleAssaies(List studySampleAssaies) {
        this.studySampleAssaies = studySampleAssaies;
    }

    /**
     * @return the closed
     */
    public String getClosed() {
        return closed;
    }

    /**
     * @param closed the closed to set
     */
    public void setClosed(String closed) {
        this.closed = closed;
    }

    

    /**
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * @param title the title to set
     */
    public void setTitle(String title) {
        this.title = title;
    }




}


